services:
  db:
    image: ahmadjanjua/devops-quote-app-db:latest
    container_name: ${DB_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - quote-vol:/var/lib/postgresql/data"
    networks:
      - app-network

  web:
    build:
      context: ./quote-app
    container_name: ${APP_NAME}
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    ports:
      - '3000:3000'
    networks:
      - app-network

volumes:
  quote-vol:

networks:
  app-network:
