services:
  quote-jenkins:
    build:
      context: .
    container_name: quote-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins-data:
    name: jenkins-data
